### ISSUE TITLE
Skype for Java throws exception while using in a newly created Group Chat 

### ISSUE THREAD

**Issue by sandeeprock12** [toomasr/skype-bot#6]
I am seeing an issue with Skype 4 Java working in group chats. It works well on old group chats but it does not work at all on new and recently created group chats. The messages are being received in a fine fashion. But, I get the below mentioned exception while sending out the message:

com.skype.CommandFailedException: Invalid/uknown chat name given
at com.skype.Utils.checkError(Utils.java:77)
at com.skype.Chat.send(Chat.java:275)
at skypePackage.MyListener.myListener(MyListener.java:113)
at skypePackage.MyListener.chatMessageReceived(MyListener.java:245)
at com.skype.ChatMessageConnectorListener.fireMessageReceived(ChatMessageConnectorListener.java:58)
at com.skype.ChatMessageConnectorListener.messageReceived(ChatMessageConnectorListener.java:38)
at com.skype.connector.Connector.fireMessageEvent(Connector.java:1119)
at com.skype.connector.Connector.access$500(Connector.java:37)
at com.skype.connector.Connector$13.run(Connector.java:1098)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

Could you throw any idea on this issue...

**Comment by p0l0us** [comment]
Hi, did you solve this problem ?

**Comment by toomasr** [comment]
Skype discontinued the API so I presume right now it is impossible to get it working.
